repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      # - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        args: [--unsafe]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      # - id: pretty-format-json
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
  - repo: https://github.com/amperser/proselint/ # config in ~/.config/proselint/config.json
    rev: "0.14.0"
    hooks:
      - id: proselint
        types: [plain-text] # / [text] # what is 'types' for?
        exclude: LICENSE
  # - repo: https://github.com/markdownlint/markdownlint # config in ~/mdlrc and ~/.config/markdownlint.
  #   rev: "v0.13.0"
  #   hooks:
  #     - id: markdownlint
  - repo: https://github.com/google/yamlfmt
    rev: "v0.13.0"
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.35.1"
    hooks:
      - id: yamllint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.16.1"
    hooks:
      - id: gitleaks
