# https://taskfile.dev

version: '3'
silent: true
tasks:
  shorts:
    desc: Show shortcuts for mac
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        echo '
        screen recording   = shift - cmd - 5
        screenshot full    = shift - cmd - 3
        screenshot partial = shift - cmd - 4
        '
  docker:
    desc: Start docker
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        open -n "/Applications/Docker.app"
  rancher:
    desc: Start rancher
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        open -n "/Application/Rancher Desktop.app"
  change-node-version:
    desc: Change node version (`task change-node-version -- 22`)
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        nvm install {{.CLI_ARGS}}
        nvm use {{.CLI_ARGS}}
  update:
    desc: Update all packages
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        # omz update # Doesn't work, as it's a function, not an application
        brew update
        brew upgrade
        brew cleanup
        softwareupdate --install --all
  update-system:
    desc: Update system
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        sudo softwareupdate --install --all --restart
  netspeed:
    desc: Show current network speed
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        networkQuality
  git-show-origin:
    desc: Show origin of current git repo
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        git ls-remote --get-url
  flush-dns:
    desc: Flush DNS on macOS
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        sudo dscacheutil -flushcache
        sudo killall -HUP mDNSResponder
  renew-dhcp:
    desc: Renew DHCP on macOS
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        sudo ipconfig set en0 BOOTP
        sudo ipconfig set en0 DHCP
  whatsmyip:
    desc: Show current public ip (v4 & v6)
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        dig @ns.sslip.io txt ip.sslip.io +short -4 | tr -d '"' # forces IPv4 lookup
        dig @ns.sslip.io txt ip.sslip.io +short -6 | tr -d '"' # forces IPv6 lookup
